// <auto-generated />
namespace SMAPP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class add_tag_columns_to_Sponsor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_tag_columns_to_Sponsor));
        
        string IMigrationMetadata.Id
        {
            get { return "201901031552308_add_tag_columns_to_Sponsor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
